% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Ant colony},
  pdfauthor={Jan Lennartz \& Andrei Chirita},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Ant colony}
\author{Jan Lennartz \& Andrei Chirita}
\date{11/22/2020}

\begin{document}
\maketitle

\newpage
\setcounter{tocdepth}{1}
\tableofcontents
\newpage

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

Ant colonies have a complex and fascinating social structure that may
bring answers to a multitude of scientific questions. Usually the nest
are organized in a stratified manner with a queen at the center and
numerous workers doing tasks needed for the upkeep of the colony. The
study for which the data we worked on was collected sought to understand
the social structure of \emph{Camponotus fellah} ants, what are the
groups inside the colonies and what factors define them.

\hypertarget{the-data}{%
\subsection{The data}\label{the-data}}

The original data of the study consist of more than 9 million observed
interactions between ants collected for 41 days from ants belonging to 6
colonies. For our project we decided to work on \ldots..

\hypertarget{preliminary-data-exploration}{%
\subsubsection{Preliminary data
exploration}\label{preliminary-data-exploration}}

In the following section we will show how the data is structured for a
single colony in a single day (namely day 17, colony 1). We will start
by loading the data using the \texttt{get\_graph} function that we built
previously and is attached to this project.

Next we will have a look at the vertices of the graph with the command
\texttt{vcount}. There are 99 of them in this graph.

Next we displayed the number of edges with the \texttt{ecount} command.
There are over 3300 edges. In detail for day 17, for the first colony
there were over 3342 interactions between 99 ants.

Each vertex has also a set of attributes like:

\begin{itemize}
\item
  Several attributes that are useful for understanding the interactions
  of the studied
\item
  Attributes that register the visits of the ant to important places of
  the colony (like the brood or the nest entrance)
\item
  The groups fitted by the authors of the study
\item
  The age of the ant (measured in days)
\item
  The body size of the ant
\end{itemize}

\hypertarget{plot}{%
\subsubsection{Plot}\label{plot}}

We will have a look at the plot of the whole network and a separate plot
for each group. The colour corresponds to the group of the ant and the
size to its degree. We see that there is a difference in the group sizes
with the nurses being the smallest group. Some ants have high degrees
while some are rather separated. Yet, there are no ants with a very high
degree. We can find some ants with a very low degree though. In general
the network looks not too heterogeneous.

\includegraphics{Report_files/figure-latex/unnamed-chunk-6-1.pdf}

\includegraphics{Report_files/figure-latex/unnamed-chunk-7-1.pdf}

As we can see the foragers and cleaners groups contain more ants than
the nurses group and they also contains more interactions. The nurses
seem to be less connected and are structured a bit differently compared
to the other groups.

\hypertarget{the-original-paper}{%
\subsection{The original paper}\label{the-original-paper}}

The original paper was written by: Danielle P. Mersch, Alessandro Crespi
and Laurent Keller and explores questions related how can we separate
ant colonies into groups and what makes ants change the group they
belong to. During their study they found 3 main groups based on the
interactions between ants and concluded that age is the main factor that
determines ants to change the group they are part of. All colonies
studied had 4-years old queens and between 122 and 192 workers per
colony. Each ant was marked and followed individually and an interaction
between two ants were defined by the fact that ``the front end of one
ant was located within thetrapezoidal shape representing the other
ant''.

\hypertarget{our-questions}{%
\subsection{Our questions}\label{our-questions}}

The goal of this work is to conduct the given data set w.r.t. various
aspects. Furthermore, a validation of the key results of the original
paper is carried out. For this a sample colony is chosen on a given day.
On this network the analysis is to be done. Certain properties will be
evaluated over multiple days when required.

We will first explore the network in a descriptive manner. This includes
characteristics like degree distribution, density, diameter and more. In
the second step we have a closer look at the groups. First, we validate
that the three groups are a valid proposal for the given network. This
is done by running a clustering algorithm on the network to identify the
groups which will be compared to the labeled groupings. Second, we
investigate how frequently ants communicate within groups and compare
this to the level of communication between groups. We answer the
question how fast information can be spread in the network and compare
this to the result of the paper. Additionally, we calculate the
centrality of specific ant or groups (e.g.~the queen) w.r.t. different
measures. Furthermore, we review several properties of the ants and
their correlation with the groups (e.g.~age, size).

\hypertarget{descriptive-statistics-of-the-network}{%
\section{Descriptive Statistics of the
network}\label{descriptive-statistics-of-the-network}}

As we noted above the data we are going to use for our analysis refers
to the movements of the ants of the first colony in day 17 of the study.
Thus the graph has 99 vertices and 3342 edges. We must also note that
the graph is connected.

\hypertarget{statistics-of-attributes}{%
\subsection{Statistics of attributes}\label{statistics-of-attributes}}

As we noted above there are several attributes that describe each ant.
In the following sub-section we will analyze two of those, namely the
age and the body size of the ant and then we will highlight differences
in regard to this attributes for each category of ants (as defined by
the authors of the study).

\hypertarget{body-size}{%
\subsubsection{Body size}\label{body-size}}

\includegraphics{Report_files/figure-latex/unnamed-chunk-9-1.pdf} It can
be easily seen that the queen has a much greater body size than the ants
of the other groups. There is little difference between ants of the
three groups in regard to this variable. Furthermore, most ants had a
body size around 150mm with just a few of them having greater body
sizes.

\begin{longtable}[]{@{}lr@{}}
\toprule
group & val\tabularnewline
\midrule
\endhead
C & 158.5950\tabularnewline
F & 164.0548\tabularnewline
N & 158.1909\tabularnewline
Q & 286.8950\tabularnewline
\bottomrule
\end{longtable}

As the data for body size for ants in groups C and F is not normally
distributed we preferred to use the Wilcoxon rank sum exact test in
order to check whether there is any difference between the means of the
body sizes of the three groups. As the results of the test yields
p-values way above 0.05 we can conclude that the three groups have
roughtly equal body sizes.

\hypertarget{age}{%
\subsubsection{Age}\label{age}}

\includegraphics{Report_files/figure-latex/unnamed-chunk-12-1.pdf}

The boxplots show that most ants have similar ages, with the exception
of the queen which is much older than the other ants. The groups do not
seem to be different in age.
\textless\textless\textless\textless\textless\textless\textless{} HEAD

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(atr[atr}\OperatorTok{$}\NormalTok{cathegory}\OperatorTok{==}\StringTok{"age"}\NormalTok{,])}\OperatorTok{+}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{val)}\OperatorTok{+}\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{binwidth=}\DecValTok{10}\NormalTok{)}\OperatorTok{+}\KeywordTok{xlab}\NormalTok{(}\StringTok{"Age in days"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Report_files/figure-latex/unnamed-chunk-13-1.pdf} The
histogram shows a pike around the age of 300 days. Most ants are younger
than 500 days and they are born in ``waves''.

\begin{longtable}[]{@{}lr@{}}
\toprule
group & val\tabularnewline
\midrule
\endhead
C & 241.4815\tabularnewline
F & 230.2000\tabularnewline
N & 192.4444\tabularnewline
Q & 1453.0000\tabularnewline
\bottomrule
\end{longtable}

There is no difference in mean age between the three groups.

\hypertarget{for-the-general-network}{%
\subsection{For the general network}\label{for-the-general-network}}

\includegraphics{Report_files/figure-latex/unnamed-chunk-17-1.pdf}

\begin{longtable}[]{@{}rrrrrr@{}}
\caption{Distribution of the degrees}\tabularnewline
\toprule
{[}0-30{]} & (30-60{]} & (60-90{]} & \textgreater90 & Min &
Max\tabularnewline
\midrule
\endfirsthead
\toprule
{[}0-30{]} & (30-60{]} & (60-90{]} & \textgreater90 & Min &
Max\tabularnewline
\midrule
\endhead
0 & 27 & 70 & 2 & 33 & 96\tabularnewline
\bottomrule
\end{longtable}

Most nodes have a rather higher degree (between 60 and 90) and there are
some nodes with a lower value of the degree, thus we can infer that most
ants had a higher number of contacts while some ants had less frequent
meetings. There is a small number of nodes that has a very high degree
(90 or over 90), they represent ants that had a lot of encounters. We
must also note that no ant had less than 33 encounters.

\hypertarget{measures-of-centrality}{%
\subsubsection{Measures of Centrality}\label{measures-of-centrality}}

\includegraphics{Report_files/figure-latex/unnamed-chunk-20-1.pdf}

In regard to betweenness centrality we can observe that one ant ranks
far over the others, thus we can conclude that there is one ant that has
a very central role in the network a conclusion we couldn't draw based
on the other measures of centrality.

The eigenvalue centrality presents a decreasing structure although it is
a smoother decrease compared to the one of the betweenes centrality, in
this case we can find no node that is much more ``central'' that the
others.

The page rank of the nodes of the graph presents a structure in which
there are several dominating nodes that have a much higher rank than the
others.

\hypertarget{average-path-length-diameter-and-clustering-coefficient}{%
\subsubsection{Average Path Length, Diameter and Clustering
Coefficient}\label{average-path-length-diameter-and-clustering-coefficient}}

The average path length can show how connected the analyzed network
is.In the case of our graph the value is approximately 1.31
(\texttt{average.path.length}). Another measure of the connectivity of
the graph is its diameter (the maximum of the series of shortest paths),
the value of the indicator is: 5 (\texttt{diameter}). The clustering
coefficient of the whole graph is 0.776 (\texttt{transitivity}), we will
compare it to those of the groups in the next sections.

\hypertarget{by-group}{%
\subsection{By group}\label{by-group}}

Before looking at the following summary statistics per group it is
important to know about the size of each group. There are 50 ants in the
group foragers, 27 cleaners and 18 are nurses. This means the following
results need to be considered under the fact of this unequal
distribution of group members.

\hypertarget{histogram-and-density}{%
\subsubsection{Histogram and Density}\label{histogram-and-density}}

The foragers have a rather wider spread of degrees compared to the other
two groups. Most of them have a degree greater than 40. The other two
groups are distributed very homogeneously. It is notable though that
there is a hierarchy of degrees starting from the low degree group of
nurses to the midrange group of cleaners over to the higher degree group
of foragers.

\includegraphics{Report_files/figure-latex/unnamed-chunk-22-1.pdf}

\includegraphics{Report_files/figure-latex/unnamed-chunk-23-1.pdf}

\hypertarget{connectivity-and-components}{%
\subsubsection{Connectivity and
Components}\label{connectivity-and-components}}

We can check the connectivity with the command \texttt{is\_connected}.
All separate groups are connected and thus, each of them form a big
component.

\hypertarget{measures-of-centrality-1}{%
\subsubsection{Measures of Centrality}\label{measures-of-centrality-1}}

We have considered many different centrality measures. Most of them have
shown a rather homogeneous distribution, meaning there was no
distinction possible between central nodes and less central nodes. For
each group the following centrality measures were decreasing smoothly
without any particular exceptional occurrences: degree centrality,
closeness centrality and eigenvalue centrality. While this can indicate
that in general there are no real distinct central nodes in the network
we can still try to find some special ants w.r.t. other centrality
measures.

Betweenness centrality: Here we see actually a decreasing structure in
all three groups. Some ants lie on the paths connecting other ants. And
some ants are rather unimportant in the network.

\includegraphics{Report_files/figure-latex/unnamed-chunk-28-1.pdf}

Pagerank: Here we can see that the foragers have a few ants who are very
important w.r.t to this centrality measure. This could indicate that
these ants are consulted by many other ants who themselves are consulted
by many ants.

\includegraphics{Report_files/figure-latex/unnamed-chunk-29-1.pdf}

\hypertarget{average-path-length-diameter-and-clustering-coefficient-1}{%
\subsubsection{Average Path Length, Diameter and Clustering
Coefficient}\label{average-path-length-diameter-and-clustering-coefficient-1}}

\begin{table}[!htbp] \centering 
  \caption{} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}} ccccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & Global & Foragers & Nurses & Cleaners \\ 
\hline \\[-1.8ex] 
Average Path Length & $1.311$ & $1.121$ & $1.092$ & $1.120$ \\ 
Diameter & $5$ & $11$ & $7$ & $4$ \\ 
Clustering & $0.776$ & $0.906$ & $0.913$ & $0.889$ \\ 
\hline \\[-1.8ex] 
\end{tabular} 
\end{table}

The average path length can be an indicator of how connected a network
is. Here the foragers and the cleaners have a similar average path
length of around 1.12. In comparison the nurses have an average path
length of 1.09, a bit smaller. All three groups are very well connected
because most ants can reach any other ant of the same group in less than
2 steps. Moreover the groups have smaller average path lengths than the
overall graph which suggests that the proposed grouping does indeed lead
to more coherent groups. The diameter is the longest shortest path in a
network and differs quite a bit in this network. The foragers have a
diameter of 11, compared to the nurses with 7 and the cleaners with 4.
This might be an indicator of a lower connection level in the group of
the foragers. There exists at least one ant who has to go over 11 other
ants in order to connect with another specially chosen ant. This is
quite extreme considering the average path length is 1.12 in this group.

Very similar results do we obtain for the clustering coefficient. All
groups are very highly connected.

If we look at the global values we see that the average path length
varies a bit from group to group compared to the global one. The
diameter varies a lot since we have each time potentially lost
connections in the subnetworks. The clustering is globally smaller than
in each group which supports the idea of those three communities in the
graph.

\hypertarget{k-means-check}{%
\subsection{K-means check}\label{k-means-check}}

\hypertarget{preparing-the-data}{%
\subsubsection{Preparing the data}\label{preparing-the-data}}

We selected the data that will be used for clustering and the auxiliary
variables that will be used to check the quality of the model. The data
to be used for clustering is:

\begin{itemize}
\item
  The score of the interactions with the queen
\item
  The score of the trips to the rubbish pile
\item
  The score of the trips to the entrance o the nest
\item
  The score of the trips to the brood
\item
  The age
\item
  The size
\item
  The foraging events
\end{itemize}

In addition we also kept the id and the group (decided of the authors of
the study) of each ant.

\includegraphics{Report_files/figure-latex/unnamed-chunk-32-1.pdf}

We first analyzed the within group error of the clustering per number of
considered groups and we conlcuded that as there is no definite point
where to make a cut the most suitable number of groups is 3 as it would
allow us to compare with the groups fitted by the authors of the study.

\begin{longtable}[]{@{}lrrr@{}}
\caption{Clustering result}\tabularnewline
\toprule
& 1 & 2 & 3\tabularnewline
\midrule
\endfirsthead
\toprule
& 1 & 2 & 3\tabularnewline
\midrule
\endhead
C & 2 & 0 & 25\tabularnewline
F & 0 & 8 & 42\tabularnewline
N & 10 & 0 & 8\tabularnewline
Q & 0 & 0 & 1\tabularnewline
\bottomrule
\end{longtable}

The results of the k-means clustering were quite underwhelming as the
model did not fit groups close to those fitted by the authors of the
study. The clustering faze was just a first look we will proceed to use
graph-specific statistical models that will allow us to have a more
conclusive conclusions weather the results of the study can be validated
or not.

\hypertarget{modeling}{%
\section{Modeling}\label{modeling}}

To get some more insights into how the network is organized and to
understand the underlying creating behavior of the network we can try to
model it. There are several ways of modeling a network. We will focus on
random networks and exponential random graph models (ERGMs). However, we
considered other network models as well but they depend on restrictions
which are not fulfilled in this network. This includes exemplary the
normality assumption for correlation networks and gaussian graphical
models. Correlation networks are based on the attributes of the network.
If the correlation between two nodes and their corresponding attributes
is high, we expect an edge between them. The attributes are assumed to
be normally distributed. AS one can see in the following plot this
assumption can not hold very much. Additionally, a Shapiro-Wilk-Tests
showed that none of the attributes are distributed normally.

\includegraphics{Report_files/figure-latex/unnamed-chunk-34-1.pdf}

\begin{longtable}[]{@{}rrrrrrr@{}}
\caption{P-Values for Shapiro-Wilk-Tests}\tabularnewline
\toprule
size & age & forage & brood & nest & rubbish & queen\tabularnewline
\midrule
\endfirsthead
\toprule
size & age & forage & brood & nest & rubbish & queen\tabularnewline
\midrule
\endhead
1e-07 & 0 & 0 & 0 & 0 & 0 & 0\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{erdos-renyi}{%
\subsection{Erdos-Renyi}\label{erdos-renyi}}

Thus we decided to focus on simpler models. To conduct the network
w.r.t. the three properties clustering coefficient, diameter and average
path length, we are using an Erdos-Renyi model. This one showed,
compared to the other possible modeling solutions the best results. In
an Erdos-Renyi graph is a graph where each pair of nodes is connected
independently with probability \(p\). It is assumed to be undirected. To
create an Erdos-Renyi graph based on our given network we can take two
network characteristics into account: The number of nodes \(n\) and the
proportion of edges \(E\) w.r.t. the possible number of edges in the
network: \(p=\frac{E}{n(n-1)/2}\). With these values we can then create
an Erdos-Renyi graph based on \(n\) and \(p\). For the given network we
find \(n=99\) and \(p=0.689\).

To be sure that the chosen \(p\) is appropriate we can also look at
different values for \(p\) and check how well the different models
perform w.r.t. the different properties.

\includegraphics{Report_files/figure-latex/unnamed-chunk-37-1.pdf}

\begin{longtable}[]{@{}rlrrlrrlrr@{}}
\toprule
\begin{minipage}[b]{0.03\columnwidth}\raggedleft
p\strut
\end{minipage} & \begin{minipage}[b]{0.11\columnwidth}\raggedright
Clustering.indicator\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\raggedleft
Clustering.values\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\raggedleft
Clustering.index\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedright
APL.indicator\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\raggedleft
APL.values\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\raggedleft
APL.index\strut
\end{minipage} & \begin{minipage}[b]{0.10\columnwidth}\raggedright
Diameter.indicator\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Diameter.values\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Diameter.index\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.005\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.003\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.005\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.661\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.005\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
4.01\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.005\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.010\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.014\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.010\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
3.460\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.010\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
9.09\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.010\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.015\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.014\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.015\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
6.096\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.015\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
15.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.015\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.020\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.022\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.020\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
5.704\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.020\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
13.73\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.020\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.025\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.025\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.025\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
4.723\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.025\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
11.04\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.025\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.030\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.030\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.030\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
4.195\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.030\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
9.29\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.030\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.035\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.037\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.035\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
3.763\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.035\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
8.27\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.035\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.040\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.040\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.040\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
3.465\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.040\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
7.54\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.040\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.045\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.042\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.045\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
3.226\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.045\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
6.67\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.045\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.050\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.048\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.050\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
3.018\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.050\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
6.01\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.050\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.055\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.054\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.055\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.880\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.055\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
5.60\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.055\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.060\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.057\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.060\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.775\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.060\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
5.25\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.060\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.065\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.066\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.065\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.663\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.065\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
5.02\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.065\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.070\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.068\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.070\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.583\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.070\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
4.88\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.070\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.075\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.074\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.075\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.502\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.075\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
4.53\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.075\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.080\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.081\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.080\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.438\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.080\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
4.22\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.080\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.085\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.084\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.085\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.380\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.085\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
4.13\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.085\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.090\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.090\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.090\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.331\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.090\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
4.03\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.090\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.095\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.094\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.095\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.284\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.095\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
4.02\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.095\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.100\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.099\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.100\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.239\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.100\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
4.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.100\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.105\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.104\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.105\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.200\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.105\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.94\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.105\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.110\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.110\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.110\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.165\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.110\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.87\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.110\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.115\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.115\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.115\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.125\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.115\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.53\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.115\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.120\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.120\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.120\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.089\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.120\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.36\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.120\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.125\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.125\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.125\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.064\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.125\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.31\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.125\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.130\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.130\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.130\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.042\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.130\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.18\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.130\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.135\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.136\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.135\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2.009\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.135\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.06\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.135\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.140\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.140\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.140\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.986\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.140\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.01\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.140\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.145\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.145\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.145\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.963\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.145\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.01\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.145\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.150\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.150\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.150\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.943\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.150\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.01\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.150\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.155\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.155\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.155\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.925\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.155\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.155\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.160\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.160\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.160\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.908\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.160\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.160\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.165\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.164\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.165\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.893\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.165\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.165\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.170\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.171\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.170\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.877\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.170\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.170\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.175\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.176\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.175\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.865\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.175\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.175\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.180\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.180\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.180\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.852\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.180\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.180\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.185\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.185\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.185\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.843\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.185\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.185\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.190\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.189\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.190\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.833\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.190\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.190\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.195\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.195\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.195\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.826\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.195\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.195\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.200\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.199\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.200\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.815\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.200\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.200\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.205\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.205\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.205\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.807\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.205\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.205\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.210\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.210\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.210\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.799\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.210\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.210\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.215\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.214\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.215\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.794\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.215\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.215\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.220\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.220\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.220\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.786\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.220\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.220\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.225\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.224\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.225\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.781\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.225\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.225\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.230\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.228\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.230\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.776\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.230\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.230\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.235\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.234\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.235\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.769\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.235\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.235\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.240\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.239\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.240\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.763\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.240\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.240\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.245\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.244\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.245\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.757\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.245\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.245\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.250\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.250\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.250\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.751\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.250\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.99\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.250\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.255\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.255\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.255\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.746\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.255\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.96\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.255\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.260\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.260\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.260\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.741\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.260\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.95\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.260\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.265\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.265\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.265\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.736\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.265\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.91\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.265\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.270\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.271\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.270\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.728\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.270\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.78\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.270\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.275\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.274\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.275\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.726\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.275\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.75\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.275\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.280\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.279\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.280\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.720\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.280\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.61\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.280\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.285\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.285\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.285\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.715\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.285\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.61\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.285\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.290\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.291\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.290\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.709\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.290\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.49\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.290\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.295\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.294\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.295\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.706\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.295\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.41\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.295\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.300\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.299\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.300\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.701\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.300\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.33\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.300\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.305\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.305\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.305\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.695\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.305\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.26\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.305\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.310\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.309\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.310\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.691\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.310\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.13\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.310\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.315\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.315\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.315\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.685\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.315\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.09\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.315\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.320\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.321\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.320\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.679\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.320\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.08\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.320\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.325\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.325\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.325\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.675\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.325\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.08\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.325\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.330\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.330\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.330\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.670\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.330\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.03\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.330\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.335\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.334\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.335\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.666\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.335\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.01\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.335\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.340\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.339\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.340\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.661\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.340\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.03\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.340\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.345\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.344\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.345\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.656\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.345\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.01\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.345\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.350\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.350\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.350\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.650\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.350\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.02\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.350\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.355\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.355\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.355\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.645\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.355\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.355\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.360\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.360\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.360\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.640\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.360\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.360\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.365\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.364\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.365\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.635\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.365\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.02\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.365\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.370\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.369\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.370\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.631\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.370\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.370\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.375\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.374\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.375\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.625\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.375\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.375\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.380\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.381\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.380\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.619\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.380\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.380\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.385\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.386\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.385\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.615\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.385\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.385\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.390\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.390\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.390\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.610\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.390\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.390\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.395\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.394\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.395\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.606\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.395\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.395\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.400\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.400\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.400\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.600\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.400\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.400\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.405\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.405\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.405\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.594\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.405\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.405\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.410\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.410\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.410\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.590\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.410\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.410\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.415\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.415\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.415\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.585\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.415\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.415\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.420\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.420\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.420\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.579\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.420\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.420\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.425\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.425\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.425\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.575\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.425\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.425\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.430\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.429\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.430\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.570\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.430\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.430\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.435\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.436\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.435\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.564\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.435\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.435\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.440\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.440\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.440\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.559\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.440\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.440\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.445\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.443\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.445\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.557\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.445\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.445\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.450\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.450\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.450\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.550\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.450\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.450\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.455\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.455\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.455\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.546\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.455\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.455\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.460\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.461\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.460\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.539\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.460\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.460\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.465\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.465\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.465\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.534\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.465\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.465\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.470\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.469\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.470\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.530\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.470\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.470\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.475\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.475\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.475\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.524\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.475\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.475\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.480\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.480\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.480\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.520\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.480\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.480\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.485\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.485\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.485\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.515\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.485\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.485\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.490\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.489\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.490\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.511\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.490\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.490\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.495\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.495\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.495\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.505\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.495\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.495\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.500\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.500\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.500\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.500\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.500\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.500\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.505\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.505\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.505\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.495\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.505\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.505\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.510\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.510\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.510\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.490\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.510\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.510\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.515\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.515\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.515\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.485\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.515\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.515\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.520\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.520\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.520\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.480\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.520\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.520\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.525\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.524\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.525\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.476\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.525\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.525\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.530\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.530\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.530\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.470\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.530\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.530\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.535\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.534\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.535\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.465\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.535\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.535\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.540\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.540\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.540\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.460\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.540\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.540\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.545\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.545\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.545\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.455\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.545\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.545\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.550\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.550\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.550\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.450\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.550\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.550\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.555\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.554\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.555\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.446\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.555\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.555\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.560\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.559\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.560\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.440\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.560\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.560\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.565\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.565\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.565\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.435\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.565\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.565\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.570\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.570\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.570\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.430\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.570\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.570\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.575\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.575\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.575\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.425\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.575\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.575\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.580\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.580\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.580\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.419\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.580\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.580\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.585\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.585\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.585\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.415\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.585\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.585\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.590\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.590\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.590\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.410\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.590\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.590\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.595\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.595\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.595\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.405\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.595\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.595\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.600\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.599\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.600\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.400\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.600\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.600\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.605\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.605\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.605\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.394\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.605\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.605\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.610\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.611\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.610\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.389\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.610\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.610\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.615\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.615\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.615\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.385\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.615\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.615\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.620\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.619\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.620\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.380\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.620\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.620\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.625\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.625\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.625\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.375\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.625\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.625\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.630\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.629\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.630\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.371\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.630\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.630\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.635\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.635\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.635\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.365\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.635\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.635\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.640\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.640\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.640\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.360\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.640\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.640\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.645\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.645\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.645\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.355\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.645\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.645\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.650\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.650\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.650\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.350\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.650\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.650\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.655\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.655\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.655\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.345\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.655\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.655\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.660\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.660\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.660\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.340\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.660\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.660\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.665\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.666\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.665\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.334\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.665\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.665\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.670\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.669\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.670\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.330\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.670\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.670\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.675\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.676\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.675\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.324\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.675\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.675\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.680\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.680\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.680\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.320\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.680\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.680\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.685\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.684\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.685\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.315\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.685\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.685\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.690\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.689\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.690\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.311\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.690\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.690\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.695\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.694\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.695\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.306\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.695\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.695\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.700\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.701\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.700\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.299\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.700\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.700\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.705\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.706\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.705\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.294\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.705\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.705\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.710\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.711\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.710\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.289\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.710\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.710\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.715\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.714\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.715\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.286\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.715\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.715\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.720\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.720\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.720\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.280\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.720\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.720\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.725\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.725\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.725\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.275\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.725\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.725\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.730\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.731\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.730\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.269\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.730\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.730\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.735\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.735\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.735\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.265\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.735\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.735\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.740\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.739\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.740\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.261\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.740\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.740\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.745\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.745\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.745\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.255\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.745\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.745\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.750\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.750\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.750\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.250\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.750\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.750\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.755\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.755\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.755\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.245\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.755\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.755\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.760\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.760\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.760\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.240\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.760\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.760\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.765\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.764\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.765\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.235\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.765\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.765\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.770\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.771\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.770\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.229\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.770\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.770\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.775\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.775\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.775\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.225\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.775\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.775\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.780\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.780\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.780\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.220\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.780\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.780\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.785\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.784\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.785\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.216\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.785\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.785\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.790\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.791\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.790\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.209\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.790\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.790\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.795\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.793\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.795\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.207\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.795\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.795\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.800\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.799\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.800\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.201\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.800\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.800\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.805\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.805\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.805\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.195\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.805\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.805\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.810\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.811\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.810\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.189\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.810\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.810\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.815\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.815\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.815\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.185\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.815\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.815\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.820\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.819\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.820\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.181\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.820\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.820\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.825\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.825\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.825\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.175\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.825\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.825\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.830\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.830\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.830\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.170\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.830\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.830\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.835\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.835\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.835\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.165\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.835\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.835\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.840\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.840\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.840\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.160\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.840\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.840\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.845\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.845\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.845\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.155\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.845\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.845\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.850\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.849\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.850\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.151\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.850\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.850\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.855\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.855\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.855\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.145\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.855\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.855\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.860\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.859\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.860\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.141\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.860\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.860\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.865\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.865\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.865\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.135\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.865\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.865\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.870\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.870\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.870\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.130\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.870\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.870\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.875\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.875\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.875\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.125\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.875\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.875\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.880\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.880\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.880\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.120\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.880\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.880\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.885\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.884\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.885\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.116\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.885\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.885\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.890\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.890\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.890\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.110\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.890\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.890\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.895\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.895\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.895\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.105\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.895\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.895\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.900\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.900\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.900\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.100\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.900\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.900\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.905\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.905\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.905\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.095\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.905\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.905\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.910\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.911\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.910\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.089\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.910\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.910\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.915\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.914\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.915\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.086\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.915\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.915\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.920\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.920\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.920\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.080\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.920\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.920\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.925\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.924\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.925\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.076\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.925\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.925\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.930\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.929\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.930\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.071\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.930\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.930\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.935\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.936\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.935\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.064\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.935\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.935\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.940\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.940\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.940\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.060\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.940\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.940\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.945\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.945\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.945\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.055\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.945\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.945\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.950\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.950\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.950\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.050\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.950\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.950\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.955\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.955\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.955\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.045\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.955\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.955\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.960\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.960\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.960\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.040\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.960\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.960\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.965\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.965\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.965\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.035\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.965\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.965\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.970\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.970\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.970\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.030\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.970\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.970\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.975\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.975\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.975\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.025\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.975\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.975\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.980\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.980\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.980\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.020\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.980\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.980\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.985\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.985\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.985\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.015\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.985\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.985\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.990\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.990\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.990\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.010\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.990\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.990\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
0.995\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.995\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
0.995\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.005\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.995\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0.995\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.03\columnwidth}\raggedleft
1.000\strut
\end{minipage} & \begin{minipage}[t]{0.11\columnwidth}\raggedright
cl\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
1.000\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
1.000\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedright
apl\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
1.000\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
di\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1.00\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1.000\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

We see then, that we get three different values for \(p\) depending of
the criterion on which we try to optimize \(p\). If we look at the
clustering coefficient we find \(p=0.8\) to be the closest to the
original network's clustering coefficient. In contrast we find \(p=0.7\)
for the average path length and \(p=0.1\) for the diameter. We can
observe that the chosen \(p=0.689\) is somehow close to the ones for the
average path length and the diameter. We note in particular that the
diameter behaves quite differently for varying \(p\) compared to the
other two properties. In order to get a high diameter we need to have a
very small \(p\). In contrast to that the other two properties seem to
fit quite well with the original network and it's value of \(p\).

Additionally, we can do a monte carlo simulation to check if it is
probable the our observed network is coming from this distribution.

\begin{longtable}[]{@{}rrr@{}}
\caption{\% of more extrem occurences in simulations}\tabularnewline
\toprule
Clustering & APL & Diameter\tabularnewline
\midrule
\endfirsthead
\toprule
Clustering & APL & Diameter\tabularnewline
\midrule
\endhead
0 & 0.507 & 0\tabularnewline
\bottomrule
\end{longtable}

We observe that the probability to get a clustering coefficient that is
greater than our observed graph is close to 0. Similarly for the
diameter of the graph. However, the average path length is not that
clear. 50.7\% of the sampled graphs hat a higher average path length
than the observed one. This shows that the model is still not perfectly
fitting. But with respect to the clustering coefficient we have an
acceptable model.

If we consider the Erdos-Renyi model we can state that the network is
based on a purely random fashion. The ants seem to connect at random.
But we need to keep in mind that the model is not perfect w.r.t the
properties average path length and diameter. Furthermore, we could
surely look at more properties of the network and take them as reference
measures as well.

\hypertarget{exponential-random-graph-models}{%
\subsection{Exponential Random Graph
Models}\label{exponential-random-graph-models}}

To capture a bit more in detail the underlying process of the network we
can try to make use of an ERGM. This allows us to take the categorical
attributes into account. We can take the groups as the most important
attribute and have a look at the resulting models. An ERGM model models
a graph which is distributed according to a distribution which belongs
to an exponential family. Again we have the number of nodes fixed and
try to find a probability of an edge between two nodes. However, in
contrast to the Erdos-Renyi graph we take into account the attributes of
the network. Thus we can make inference about the edges when we look at
two specific nodes. If node \(X\) is of class \(A\) and node \(Y\) of
class \(B\) the probability of a tie between those two might be
different compared to the case where both nodes are from the same class.

When creating a model we can first just look at the edges. We do not
include any attributes yet. We make use of the function \texttt{ergm}
and need to use \texttt{plogis} to transform the coefficients to
probabilities.

The probability for an edge between two nodes regardless of their
attributes is \(0.689\). This is exactly the same as we found earlier.

If we now introduce the attribute \emph{group} and check for the
matching probability we find \(0.88\).

This means that nodes who have the same group have a much higher
probability of having a tie: \(p=0.88\). This confirms what was found in
the paper. To check the validity of the model we can check the goodness
of fit.

\begin{figure}
\centering
\includegraphics{gof.png}
\caption{Goodness of fit}
\end{figure}

As we can see the result is not very accurate. With respect to the
minimum geodesic distance we find a fit that is okay. But for the degree
and edge-wise shared partners the model does not fit the data very well.
Therefore, we need to be careful with interpreting this model as well.
Nevertheless, we can state that we find a similar tendency like the
authors of the paper did. Ants of the same group have a higher chance of
a tie.

In general we can say that the given models do not fit the network very
well. We do not show the other models here that were tried but did
perform even worse. This could be caused by an unusual behavior of the
network. It might be very difficult to find a good fitting model. There
seems to be a lot of randomness besides from some structure going on in
the network. Even though we could not find a perfect model, the proposed
models indicate that the network is very densely connected and that the
groups that were found are reasonable.

\hypertarget{key-points-and-conclusions}{%
\section{Key points and conclusions}\label{key-points-and-conclusions}}

\hypertarget{key-points}{%
\subsubsection{Key points}\label{key-points}}

In our project we tried to check the results of a graph-based experiment
on ant behavior. In order to do that we applied varied methods before
that we decided to check the characteristics of the cervices. During
that faze we found which were the main characteristics included by the
data, created plots and did statistical testing on them i order to be
able to tell if the groups fitted by the authors of the original study
were different from each other. In the next phase we described the
structure of the graph and the sub-graphs defined by the groups by
applying measures of node centrality and verifying the distribution of
the degrees of the nodes. In the third phase of our projects we created
a k-mean model in order to check if we can find the fitted groups by
using only the vertex attributes. The next phase was dedicated to graph
specific models. On that part of the project we mainly focused on two
models the Erdos-Renyi random graph, the model produced results quite
close to those of the original graph we analyzed. After a first check we
implemented a cross-validation algorithm in order to determine the
optimal values of the main parameters of the Erdos-Renyi random graph.
Then we did a Monte Carlo Simulation in order to determine if our
network can be considered a random graph. The results show that it is a
random graph though one imperfect w.r.t the properties average path
length and diameter. In this case a further modeling of the graph is
required, thus we tried to use exponential an exponential random graph
model which yielded mixed results.

\hypertarget{conclusions}{%
\subsubsection{Conclusions}\label{conclusions}}

\hypertarget{statement-of-division-of-labor}{%
\section{Statement of Division of
Labor}\label{statement-of-division-of-labor}}

\emph{Jan Lennartz}: I performed the statistical analysis by group and
took care of the main plot of the network. I conducted the different
models and analyzed the ER and ERGM models. Additionally, I introduced
our main questions. \emph{Andrei Chirita}: I performed the statistical
analysis for the whole dataset and took care of the statistical test
that determined whether there are differences between groups in regard
to age and body size. I also did the k-means model and took care of data
description and stating the key points of the project.

\end{document}
